# Generated by Django 4.2 on 2023-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_city_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Не выбрано'), ('m', 'Мужской'), ('f', 'Женский')], max_length=50, verbose_name='Пол'),
        ),
    ]
