# Generated by Django 4.2 on 2023-05-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='users/profile.png', null=True, upload_to='', verbose_name='Фото профиля'),
        ),
    ]
