# Generated by Django 4.2 on 2023-05-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_message_image_messagemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemedia',
            name='image',
            field=models.ImageField(upload_to='chat/'),
        ),
    ]
