# Generated by Django 4.2 on 2023-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_messagemedia_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemedia',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
