# Generated by Django 4.2 on 2023-05-05 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_messagemedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemedia',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='chat.message'),
        ),
    ]
