# Generated by Django 4.2 on 2023-05-07 19:20

import chat.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_messagemedia_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=chat.fields.EncryptedMessageField(),
        ),
    ]
