# Generated by Django 4.2 on 2023-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
