# Generated by Django 4.2 on 2023-04-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_age_user_birthday'),
        ('catalogue', '0004_ad_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.city'),
        ),
    ]
