# Generated by Django 4.2 on 2023-04-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_city_alter_user_gender'),
        ('catalogue', '0006_alter_ad_city_alter_ad_created_at_alter_ad_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Город', to='account.city'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Опыт', to='catalogue.experience'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Предмет', to='catalogue.subject'),
        ),
    ]
