# Generated by Django 4.2 on 2023-04-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_ad_city_alter_ad_experience_alter_ad_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
