# Generated by Django 4.2 on 2023-04-28 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_alter_user_city_alter_user_gender'),
        ('catalogue', '0008_alter_ad_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.experience', verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.subject', verbose_name='Предмет'),
        ),
    ]
