# Generated by Django 4.2 on 2023-04-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_ad_city_alter_ad_creator_alter_ad_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='creator_role',
            field=models.CharField(choices=[('s', 'Ученик'), ('t', 'Учитель')], default='t', max_length=50, verbose_name='Репетитор или Ученик'),
            preserve_default=False,
        ),
    ]
