# Generated by Django 4.2 on 2023-04-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_ad_creator_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='creator_role',
            field=models.CharField(choices=[('t', 'Репетитор'), ('s', 'Ученик')], default='t', max_length=50, verbose_name='Кто вы?'),
        ),
    ]
