# Generated by Django 4.2 on 2023-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_alter_ad_creator_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ad',
            name='creator_role',
            field=models.CharField(choices=[('', 'Не выбрано'), ('t', 'Репетитор'), ('s', 'Ученик')], default='t', max_length=50, verbose_name='Кто вы?'),
        ),
    ]
