# Generated by Django 4.2 on 2023-04-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_alter_ad_options_alter_ad_creator_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='subject',
        ),
        migrations.AddField(
            model_name='ad',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='catalogue.subject', verbose_name='Предмет'),
        ),
    ]
