# Generated by Django 4.2 on 2023-04-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_remove_ad_subject_ad_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='subject',
            field=models.ManyToManyField(to='catalogue.subject', verbose_name='Предмет'),
        ),
    ]
